/**
 * Business Listings Data
 * In production, this should be fetched from a backend API
 * Example: fetch('/api/listings').then(res => res.json())
 */
window.LISTINGS = [
  {
    id: "sharma-general-store",
    name: "Sharma General Store",
    category: "Grocery & Supermarkets",
    categorySlug: "grocery",
    featured: true,
    status: "open",
    rating: 4.2,
    reviewCount: 38,
    address: "12 Main Market Road, Sector 4, Your City",
    mapLink: "https://maps.google.com/?q=Sharma+General+Store",
    phone: "+91 98765 43210",
    email: "sharma@example.com",
    website: "",
    whatsapp: "+91 98765 43210",
    hours: {mon:{open:"07:00",close:"22:00"},tue:{open:"07:00",close:"22:00"},wed:{open:"07:00",close:"22:00"},thu:{open:"07:00",close:"22:00"},fri:{open:"07:00",close:"22:00"},sat:{open:"07:00",close:"22:00"},sun:{open:"08:00",close:"21:00"}},
    description: "A trusted neighborhood general store offering groceries, dairy products, and stationery since 1998.",
    tags: ["grocery","dairy","stationery","local"],
    isNew: false
  },
  {
    id: "sagar-restaurant",
    name: "Sagar Restaurant",
    category: "Restaurants & Food",
    categorySlug: "restaurants",
    featured: true,
    status: "open",
    rating: 4.6,
    reviewCount: 124,
    address: "45 Ocean Road, Near City Park, Your City",
    mapLink: "https://maps.google.com/?q=Sagar+Restaurant",
    phone: "+91 91234 56789",
    email: "sagar@foodmail.com",
    website: "https://sagar.example.com",
    whatsapp: "+91 91234 56789",
    hours: {mon:{open:"11:00",close:"23:00"},tue:{open:"11:00",close:"23:00"},wed:{open:"11:00",close:"23:00"},thu:{open:"11:00",close:"23:00"},fri:{open:"11:00",close:"23:30"},sat:{open:"11:00",close:"23:30"},sun:{open:"11:00",close:"22:00"}},
    description: "Popular seafood and regional cuisine with relaxed dining and family-friendly atmosphere.",
    tags: ["seafood","dinner","family"],
    isNew: false
  },
  {
    id: "medcare-pharmacy",
    name: "MedCare Pharmacy",
    category: "Pharmacy & Health",
    categorySlug: "pharmacy",
    featured: false,
    status: "open",
    rating: 4.1,
    reviewCount: 56,
    address: "7 Health Plaza, Sector 1, Your City",
    mapLink: "https://maps.google.com/?q=MedCare+Pharmacy",
    phone: "+91 99876 54321",
    email: "contact@medcare.com",
    website: "",
    whatsapp: "+91 99876 54321",
    hours: {mon:{open:"09:00",close:"21:00"},tue:{open:"09:00",close:"21:00"},wed:{open:"09:00",close:"21:00"},thu:{open:"09:00",close:"21:00"},fri:{open:"09:00",close:"21:00"},sat:{open:"10:00",close:"20:00"},sun:{open:"10:00",close:"18:00"}},
    description: "24/7 neighborhood pharmacy providing prescriptions, wellness products and consultations.",
    tags: ["pharmacy","medicine","wellness"],
    isNew: false
  },
  {
    id: "city-bank-branch",
    name: "City Bank — MG Road Branch",
    category: "Banks & Finance",
    categorySlug: "banks",
    featured: false,
    status: "closed",
    rating: 4.0,
    reviewCount: 22,
    address: "MG Road 101, Financial District, Your City",
    mapLink: "https://maps.google.com/?q=City+Bank+MG+Road",
    phone: "+91 90123 45678",
    email: "mgroad@citybank.com",
    website: "https://citybank.example.com",
    whatsapp: "",
    hours: {mon:{open:"10:00",close:"16:00"},tue:{open:"10:00",close:"16:00"},wed:{open:"10:00",close:"16:00"},thu:{open:"10:00",close:"16:00"},fri:{open:"10:00",close:"16:00"},sat:{open:"00:00",close:"00:00"},sun:{open:"00:00",close:"00:00"}},
    description: "Full-service bank branch offering retail and SME banking solutions.",
    tags: ["bank","atm","finance"],
    isNew: false
  },
  {
    id: "bright-minds-tuition",
    name: "Bright Minds Tuition Center",
    category: "Education & Schools",
    categorySlug: "education",
    featured: false,
    status: "open",
    rating: 4.8,
    reviewCount: 64,
    address: "8 Knowledge Lane, Near Library, Your City",
    mapLink: "https://maps.google.com/?q=Bright+Minds+Tuition",
    phone: "+91 98765 11223",
    email: "hello@brightminds.edu",
    website: "",
    whatsapp: "+91 98765 11223",
    hours: {mon:{open:"09:00",close:"18:00"},tue:{open:"09:00",close:"18:00"},wed:{open:"09:00",close:"18:00"},thu:{open:"09:00",close:"18:00"},fri:{open:"09:00",close:"18:00"},sat:{open:"09:00",close:"14:00"},sun:{open:"00:00",close:"00:00"}},
    description: "Expert tutors for maths, science & languages with small group classes.",
    tags: ["tuition","coaching","kids"],
    isNew: false
  },
  {
    id: "lavish-salon",
    name: "Lavish Salon & Spa",
    category: "Salons & Beauty",
    categorySlug: "salons",
    featured: true,
    status: "open",
    rating: 4.4,
    reviewCount: 89,
    address: "22 Beauty Street, Mall Road, Your City",
    mapLink: "https://maps.google.com/?q=Lavish+Salon",
    phone: "+91 91222 33344",
    email: "bookings@lavishspa.com",
    website: "",
    whatsapp: "+91 91222 33344",
    hours: {mon:{open:"10:00",close:"20:00"},tue:{open:"10:00",close:"20:00"},wed:{open:"10:00",close:"20:00"},thu:{open:"10:00",close:"20:00"},fri:{open:"10:00",close:"21:00"},sat:{open:"10:00",close:"21:00"},sun:{open:"11:00",close:"18:00"}},
    description: "Premium salon and spa offering hair, skin and wellness treatments.",
    tags: ["salon","spa","beauty"],
    isNew: true
  },
  {
    id: "rajan-hardware",
    name: "Rajan Hardware & Tools",
    category: "Hardware & Repairs",
    categorySlug: "hardware",
    featured: false,
    status: "open",
    rating: 4.0,
    reviewCount: 14,
    address: "5 Industrial Estate, Sector 7, Your City",
    mapLink: "https://maps.google.com/?q=Rajan+Hardware",
    phone: "+91 93333 44455",
    email: "",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"09:00",close:"19:00"},tue:{open:"09:00",close:"19:00"},wed:{open:"09:00",close:"19:00"},thu:{open:"09:00",close:"19:00"},fri:{open:"09:00",close:"19:00"},sat:{open:"09:00",close:"16:00"},sun:{open:"00:00",close:"00:00"}},
    description: "Local provider of tools, fittings and repair supplies for homes and tradespeople.",
    tags: ["tools","repairs","hardware"],
    isNew: false
  },
  {
    id: "city-hospital",
    name: "City Hospital & Diagnostics",
    category: "Hospitals & Clinics",
    categorySlug: "hospitals",
    featured: true,
    status: "open",
    rating: 4.3,
    reviewCount: 210,
    address: "1 Health Avenue, Medical District, Your City",
    mapLink: "https://maps.google.com/?q=City+Hospital",
    phone: "+91 90000 11122",
    email: "info@cityhospital.com",
    website: "https://cityhospital.example.com",
    whatsapp: "",
    hours: {mon:{open:"00:00",close:"23:59"},tue:{open:"00:00",close:"23:59"},wed:{open:"00:00",close:"23:59"},thu:{open:"00:00",close:"23:59"},fri:{open:"00:00",close:"23:59"},sat:{open:"00:00",close:"23:59"},sun:{open:"00:00",close:"23:59"}},
    description: "24-hour multi-specialty hospital with emergency and diagnostic services.",
    tags: ["hospital","emergency","diagnostics"],
    isNew: false
  },
  {
    id: "spark-laundry",
    name: "Spark Laundry",
    category: "Laundry & Cleaning",
    categorySlug: "laundry",
    featured: false,
    status: "open",
    rating: 4.2,
    reviewCount: 33,
    address: "14 Clean Lane, Near Bus Stand, Your City",
    mapLink: "https://maps.google.com/?q=Spark+Laundry",
    phone: "+91 94444 55566",
    email: "spark@laundry.com",
    website: "",
    whatsapp: "+91 94444 55566",
    hours: {mon:{open:"08:00",close:"20:00"},tue:{open:"08:00",close:"20:00"},wed:{open:"08:00",close:"20:00"},thu:{open:"08:00",close:"20:00"},fri:{open:"08:00",close:"20:00"},sat:{open:"08:00",close:"18:00"},sun:{open:"10:00",close:"16:00"}},
    description: "Quick turnaround laundry and dry-cleaning service with pickup options.",
    tags: ["laundry","dryclean","pickup"],
    isNew: false
  },
  {
    id: "express-delivery",
    name: "Express Delivery Co.",
    category: "Delivery & Logistics",
    categorySlug: "delivery",
    featured: false,
    status: "open",
    rating: 3.9,
    reviewCount: 45,
    address: "Warehouse 3, Logistics Park, Your City",
    mapLink: "https://maps.google.com/?q=Express+Delivery",
    phone: "+91 97777 66655",
    email: "support@expressd.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"08:00",close:"22:00"},tue:{open:"08:00",close:"22:00"},wed:{open:"08:00",close:"22:00"},thu:{open:"08:00",close:"22:00"},fri:{open:"08:00",close:"22:00"},sat:{open:"09:00",close:"18:00"},sun:{open:"09:00",close:"18:00"}},
    description: "Reliable local delivery and courier services for businesses and individuals.",
    tags: ["delivery","logistics","courier"],
    isNew: false
  },
  {
    id: "royal-petrol-pump",
    name: "Royal Petrol Pump",
    category: "Petrol Stations",
    categorySlug: "pump",
    featured: false,
    status: "open",
    rating: 4.0,
    reviewCount: 19,
    address: "Highway 8, Mile 12, Your City",
    mapLink: "https://maps.google.com/?q=Royal+Petrol+Pump",
    phone: "+91 98888 77766",
    email: "",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"00:00",close:"23:59"},tue:{open:"00:00",close:"23:59"},wed:{open:"00:00",close:"23:59"},thu:{open:"00:00",close:"23:59"},fri:{open:"00:00",close:"23:59"},sat:{open:"00:00",close:"23:59"},sun:{open:"00:00",close:"23:59"}},
    description: "24/7 petrol station with convenience store and air/water facilities.",
    tags: ["fuel","24x7","convenience"],
    isNew: false
  },
  {
    id: "star-cinema",
    name: "Star Cinema Multiplex",
    category: "Entertainment & Leisure",
    categorySlug: "entertainment",
    featured: false,
    status: "open",
    rating: 4.5,
    reviewCount: 310,
    address: "Cinema Complex, Downtown, Your City",
    mapLink: "https://maps.google.com/?q=Star+Cinema",
    phone: "+91 90909 80808",
    email: "boxoffice@starcinema.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"10:00",close:"23:00"},tue:{open:"10:00",close:"23:00"},wed:{open:"10:00",close:"23:00"},thu:{open:"10:00",close:"23:00"},fri:{open:"10:00",close:"00:00"},sat:{open:"10:00",close:"00:00"},sun:{open:"10:00",close:"23:00"}},
    description: "Latest blockbusters and premium screens for an unmatched experience.",
    tags: ["movies","entertainment","family"],
    isNew: false
  },
  {
    id: "green-inn-hotel",
    name: "Green Inn Hotel",
    category: "Hotels & Stays",
    categorySlug: "hotels",
    featured: false,
    status: "open",
    rating: 4.1,
    reviewCount: 98,
    address: "Hotel Row, Central Avenue, Your City",
    mapLink: "https://maps.google.com/?q=Green+Inn+Hotel",
    phone: "+91 98811 22334",
    email: "stay@greeninn.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"00:00",close:"23:59"},tue:{open:"00:00",close:"23:59"},wed:{open:"00:00",close:"23:59"},thu:{open:"00:00",close:"23:59"},fri:{open:"00:00",close:"23:59"},sat:{open:"00:00",close:"23:59"},sun:{open:"00:00",close:"23:59"}},
    description: "Comfortable stays with modern amenities, near transport hubs.",
    tags: ["hotel","accommodation","booking"],
    isNew: false
  },
  {
    id: "legal-aid-office",
    name: "Legal Aid & Services",
    category: "Legal & Government",
    categorySlug: "legal",
    featured: false,
    status: "open",
    rating: 3.8,
    reviewCount: 12,
    address: "Civic Center, Block B, Your City",
    mapLink: "https://maps.google.com/?q=Legal+Aid+Office",
    phone: "+91 97700 11223",
    email: "info@legalaid.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"10:00",close:"17:00"},tue:{open:"10:00",close:"17:00"},wed:{open:"10:00",close:"17:00"},thu:{open:"10:00",close:"17:00"},fri:{open:"10:00",close:"17:00"},sat:{open:"00:00",close:"00:00"},sun:{open:"00:00",close:"00:00"}},
    description: "Assistance with government forms, legal advice and documentation services.",
    tags: ["legal","documents","government"],
    isNew: true
  },
  {
    id: "mountain-cafe",
    name: "Mountain Cafe",
    category: "Restaurants & Food",
    categorySlug: "restaurants",
    featured: false,
    status: "open",
    rating: 4.5,
    reviewCount: 76,
    address: "Cafe Lane, Hillview, Your City",
    mapLink: "https://maps.google.com/?q=Mountain+Cafe",
    phone: "+91 91111 22233",
    email: "hello@mountaincafe.com",
    website: "",
    whatsapp: "+91 91111 22233",
    hours: {mon:{open:"08:00",close:"22:00"},tue:{open:"08:00",close:"22:00"},wed:{open:"08:00",close:"22:00"},thu:{open:"08:00",close:"22:00"},fri:{open:"08:00",close:"23:00"},sat:{open:"08:00",close:"23:00"},sun:{open:"09:00",close:"21:00"}},
    description: "Cozy cafe serving breakfast, artisanal coffees and light bites.",
    tags: ["cafe","breakfast","coffee"],
    isNew: false
  },
  {
    id: "green-grocery-farm",
    name: "Green Grocery Farm",
    category: "Grocery & Supermarkets",
    categorySlug: "grocery",
    featured: false,
    status: "open",
    rating: 4.0,
    reviewCount: 40,
    address: "Farm Road 9, Your City",
    mapLink: "https://maps.google.com/?q=Green+Grocery+Farm",
    phone: "+91 92222 33344",
    email: "contact@greengrocery.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"07:00",close:"21:00"},tue:{open:"07:00",close:"21:00"},wed:{open:"07:00",close:"21:00"},thu:{open:"07:00",close:"21:00"},fri:{open:"07:00",close:"21:00"},sat:{open:"07:00",close:"21:00"},sun:{open:"08:00",close:"20:00"}},
    description: "Fresh produce and organic groceries sourced locally.",
    tags: ["organic","fresh","grocery"],
    isNew: false
  },
  {
    id: "healwell-clinic",
    name: "HealWell Clinic",
    category: "Hospitals & Clinics",
    categorySlug: "hospitals",
    featured: false,
    status: "open",
    rating: 4.2,
    reviewCount: 58,
    address: "Clinic Street 12, Medical Hub, Your City",
    mapLink: "https://maps.google.com/?q=HealWell+Clinic",
    phone: "+91 93311 44556",
    email: "appointments@healwell.com",
    website: "",
    whatsapp: "+91 93311 44556",
    hours: {mon:{open:"09:00",close:"17:00"},tue:{open:"09:00",close:"17:00"},wed:{open:"09:00",close:"17:00"},thu:{open:"09:00",close:"17:00"},fri:{open:"09:00",close:"17:00"},sat:{open:"10:00",close:"14:00"},sun:{open:"00:00",close:"00:00"}},
    description: "General practitioners and specialists with diagnostic services.",
    tags: ["clinic","doctors","appointments"],
    isNew: false
  },
  {
    id: "urban-guesthouse",
    name: "Urban Guesthouse",
    category: "Hotels & Stays",
    categorySlug: "hotels",
    featured: false,
    status: "open",
    rating: 4.0,
    reviewCount: 31,
    address: "Guest Lane 3, Old Town, Your City",
    mapLink: "https://maps.google.com/?q=Urban+Guesthouse",
    phone: "+91 91919 19191",
    email: "stay@urbanguest.com",
    website: "",
    whatsapp: "",
    hours: {mon:{open:"00:00",close:"23:59"},tue:{open:"00:00",close:"23:59"},wed:{open:"00:00",close:"23:59"},thu:{open:"00:00",close:"23:59"},fri:{open:"00:00",close:"23:59"},sat:{open:"00:00",close:"23:59"},sun:{open:"00:00",close:"23:59"}},
    description: "Budget guesthouse ideal for short stays and travelers.",
    tags: ["guesthouse","budget","stay"],
    isNew: true
  }
];

/**
 * Sanitize HTML to prevent XSS attacks
 */
function sanitizeHTML(str) {
  const temp = document.createElement('div');
  temp.textContent = str;
  return temp.innerHTML;
}

/**
 * Render business card component
 * @param {Object} b - Business object
 * @returns {string} HTML string for business card
 */
window.renderCard = function(b){
  const name = sanitizeHTML(b.name);
  const desc = sanitizeHTML(b.description.slice(0,120));
  const tags = b.tags.slice(0,3).map(t => `<span class="tag">${sanitizeHTML(t)}</span>`).join('');
  
  return `
  <article class="card ${b.featured ? 'featured' : ''}" role="article">
    <div class="meta">
      <div class="title"><a href="business-detail.html?id=${encodeURIComponent(b.id)}">${name}</a></div>
      <div class="small" aria-label="Rating ${b.rating} out of 5 stars">${b.rating} ★ (${b.reviewCount})</div>
    </div>
    <div class="desc">${desc}...</div>
    <div class="tags">${tags}</div>
  </article>
  `;
};
